<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>5.0.3</Version>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <PackageId>Npap.Yarp.ReverseProxy.OpenApi</PackageId>

        <IncludeSymbols>True</IncludeSymbols>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageReleaseNotes>Update Project Dependencies</PackageReleaseNotes>
        <Description>YARP-OpenAPI - Serve a single OpenApi doc with YARP by merging OpenAPI docs aggregated from multiple microservices.</Description>

        <Authors>Andrei Tsaregorodtsev, Nick Papadiochos</Authors>
        <PackageProjectUrl>https://github.com/npapadiochos/YARP-OpenApi</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\LICENSE.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>
  
    <ItemGroup>
        <PackageReference Include="IdentityModel.AspNetCore" Version="4.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
        <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.28" />
        <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

</Project>
